name: Test Automation CI 

on:
  push:
    branches: [ ft_module_enhancement ]   

jobs:

  smoke:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Navigate to web folder
        run: cd web
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache: 'npm'
      - name: Install dependencies and Run web test
      - run: npm install
      - run: npm run smoke

  MochaTests:
    needs: [smoke]  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.17.6
        cache: 'npm'
    - run: npm install
    - run: npm run test
    - run: npm run report:mocha:ci

    - name: Generate Mochawesome Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: MochawesomeReport
        path: mochawesome-report

  CucumberBDDTests:
    needs: [smoke]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
        cache: 'npm'
    - run: npm install
    - run: npm run test:e2e
    - run: npm run report:cucumber

    - name: Generate Cucumber HTML Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: CucumberHTMLReport
        path: reports/cucumber/cucumber-report.html