name: WebDriverIOTypeScript Test Automation Framework CI 

on:
  pull_request:
    branches: [ master ]

jobs:
  MochaTests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
        cache: 'npm'
    - run: npm install
    - run: npm run test

    - name: Generate Mochawesome Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: MochawesomeReport
        path: mochawesome-report

  CucumberBDDTests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
        cache: 'npm'
    - run: npm install
    - run: npm run test:e2e

    - name: Generate Cucumber HTML Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: CucumberHTMLReport
        path: reports/cucumber/cucumber-report.html